apiVersion: v1
kind: Service
metadata:
  name: tabibayashi-app
  labels:
    name: tabibayashi-app
spec:
  ports:
  - port: 80
    targetPort: 1323
  selector:
    name: tabibayashi-app
  type: LoadBalancer
