apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tabibayashi-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: tabibayashi-app
    spec:
      containers:
      - name: tabibayashi-app
        image: gcr.io/kyotohack19-team-a/tabibayashi-app:0.6
        ports:
        - containerPort: 1323
        env:
        - name: REDIS_HOST
          value: tabibayashi-redis-master