apiVersion: v1
kind: Service
metadata:
  name: tabibayashi-redis-master
  labels:
    name: tabibayashi-redis-master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: tabibayashi-redis-master
